name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure Data
      run: ./configure
      
    - name: Make Minishell2
      run: make
      
    - name: Test if Minishell2 works
      run: echo "echo Hello world!" | ./mysh
      
    - name: Execute unit tests
      run: make tests_run
